In [1]:
import numpy as np

In [4]:
# Load the provided npy file to inspect its format
npy_file_path = 'humanml3d_kinect_data.npy'
npy_data = np.load(npy_file_path)

# Checking the shape and some data to understand its format
npy_data_shape = npy_data.shape
npy_data_sample = npy_data[0]  # First frame data sample

npy_data_shape, npy_data_sample

((90, 22, 3),
 array([[ -31.06007767, -367.56033325, 3225.3425293 ],
        [ 165.09561157,  -13.10750866, 3242.16333008],
        [ 209.60160828,  308.92736816, 3404.73974609],
        [ 246.72831726,  451.77142334, 3305.27246094],
        [ -76.18505096,    6.24191761, 3317.25390625],
        [ -44.07494736,  340.17141724, 3466.82885742],
        [ -52.7856369 ,  456.36907959, 3351.7800293 ],
        [ -54.55667114, -658.24169922, 3136.63867188],
        [ -65.83004761, -863.89550781, 3125.60498047],
        [ -32.26570511, -832.15332031, 3131.45800781],
        [ -40.11480331, -906.02050781, 2962.71020508],
        [ -22.75168228, -952.97290039, 2980.64453125],
        [ 100.53323364, -806.65930176, 3144.06176758],
        [ 223.91781616, -641.54528809, 3306.66064453],
        [ 251.53535461, -425.21810913, 3338.17431641],
        [ 231.58744812, -352.36593628, 3286.56469727],
        [-211.6754303 , -786.38043213, 3103.9440918 ],
        [-346.56011963, -614.64447021, 3258.4440918

In [4]:
# Load the provided npy file to inspect its format
npy_file_path = 'npyfolder/take-1_DEFAULT_RKK.npy'
npy_data = np.load(npy_file_path)

# Checking the shape and some data to understand its format
npy_data_shape = npy_data.shape
npy_data_sample = npy_data[0]  # First frame data sample

npy_data_shape, npy_data_sample

((843, 74, 3),
 array([[ 0.00000000e+00,  9.40000000e+01,  0.00000000e+00],
        [ 8.10000000e+00,  9.40000000e+01,  0.00000000e+00],
        [ 8.10000000e+00,  5.08000000e+01,  0.00000000e+00],
        [ 8.16300000e+00,  7.50000000e+00, -3.85763742e-18],
        [ 8.16300000e+00,  1.26900000e+00,  1.31520000e+01],
        [ 8.16300000e+00,  1.40000000e-02,  2.05880000e+01],
        [-8.10000000e+00,  9.40000000e+01,  0.00000000e+00],
        [-8.10000000e+00,  5.08000000e+01,  0.00000000e+00],
        [-8.16300000e+00,  7.50000000e+00,  1.15729123e-17],
        [-8.16300000e+00,  1.26900000e+00,  1.31520000e+01],
        [-8.16300000e+00,  1.40000000e-02,  2.05880000e+01],
        [ 0.00000000e+00,  1.02484000e+02, -3.94800000e+00],
        [-9.29874315e-16,  1.10077000e+02, -3.94800000e+00],
        [-1.85974863e-15,  1.17670000e+02, -3.94800000e+00],
        [-3.42999076e-15,  1.30492000e+02, -3.94800000e+00],
        [ 7.04000000e+00,  1.42931000e+02, -2.03300000e+00],
        [

In [6]:


# Load the .npz file
npy_file_path = 'body_tracking_data_with_metadata.npz'
npy_data = np.load(npy_file_path)

# Checking the content of the file (array keys)
npy_data_keys = npy_data.files  # Get the keys of the stored arrays
print("Keys in npz file:", npy_data_keys)

# Inspect each array in the file
for key in npy_data_keys:
    array_data = npy_data[key]
    print(f"\nKey: '{key}'")
    print(f"Shape: {array_data.shape}")
    print(f"Data type: {array_data.dtype}")
    
    # Check if the array has more than 0 dimensions
    if array_data.ndim > 0:
        # Print a small sample of the array data (first frame or sample)
        print(f"Sample data from '{key}':\n", array_data[0])  # First frame or first element
    else:
        # For 0-dimensional arrays, just print the value
        print(f"Value: {array_data}")


Keys in npz file: ['trans', 'poses', 'betas', 'dmpls', 'gender', 'mocap_framerate']

Key: 'trans'
Shape: (10, 3)
Data type: float64
Sample data from 'trans':
 [203.62843323 146.77528381 564.56646729]

Key: 'poses'
Shape: (10, 32)
Data type: float64
Sample data from 'poses':
 [-0.40889689 -0.41464087 -0.47913954  0.51900852  0.6736396   0.69289303
  0.29155132  0.30861214  0.12781741  0.12781741  0.28942621  0.72504467
  0.51736021  0.51437765  0.6413368   0.70405447  0.70405447  0.71615839
 -0.25568327  0.56182408  0.54535747  0.735174    0.60912293  0.43262577
  0.45524967 -0.01859342  0.61283833  0.61283833  0.72186327  0.40803054
  0.72186327  0.61283833]

Key: 'betas'
Shape: (16,)
Data type: float64
Sample data from 'betas':
 0.22564885682670754

Key: 'dmpls'
Shape: (10, 8)
Data type: float64
Sample data from 'dmpls':
 [0.76306169 0.49781496 0.53357842 0.18156757 0.16484907 0.81027896
 0.41358967 0.10955413]

Key: 'gender'
Shape: ()
Data type: <U4
Value: male

Key: 'mocap_framerate